apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: krane-ops-view
    component: frontend
  name: krane-ops-view
spec:
  replicas: 1
  selector:
    matchLabels:
      application: krane-ops-view
      component: frontend
  template:
    metadata:
      labels:
        application: krane-ops-view
        component: frontend
    spec:
      serviceAccountName: krane-ops-view
      containers:
      - name: service
        # see https://github.com/hjacobs/kube-ops-view/releases
        image: dumonet/krane-ops-view
        args:
        # remove this option to use built-in memory store
        - --redis-url=redis://krane-ops-view-redis:6379
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: PROMURL
          valueFrom:
            configMapKeyRef:
              name: krane-ops-view
              key: promURL
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
