apiVersion: v1
kind: Service
metadata:
  labels:
    application: krane-ops-view
    component: redis
  name: krane-ops-view-redis
spec:
  selector:
    application: krane-ops-view
    component: redis
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
