apiVersion: v1
kind: Service
metadata:
  labels:
    application: thkim-ops-view
    component: frontend
  name: thkim-ops-view
spec:
  selector:
    application: thkim-ops-view
    component: frontend
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 31379
